import type { Question } from "./types"

/** 由 data/exam-paper.md 自动生成，请勿手改；更新题库请改 md 后运行 node scripts/parse-exam-paper.mjs */

export const examPaperChoiceQuestions: Question[] = [
{ id: 1, type: "choice" as const, content: "擦伤形成的表皮组织出血或组织液渗出，以下处理方法正确的是", options: [{ key: "A", text: "用冰袋冷敷伤口" }, { key: "B", text: "热敷伤口止血" }, { key: "C", text: "生理盐水洗净创面，消毒止血" }], answer: "C" },
{ id: 2, type: "choice" as const, content: "运动中出现踝关节扭伤，以下处理方法正确的是", options: [{ key: "A", text: "停止运动，马上热敷" }, { key: "B", text: "停止运动，立即按摩" }, { key: "C", text: "停止运动，进行冷敷" }], answer: "C" },
{ id: 3, type: "choice" as const, content: "接开水时手被烫伤，以下处理方法正确的是", options: [{ key: "A", text: "尽快用凉水冲，降低伤处温度" }, { key: "B", text: "涂抹紫药水或红药水" }, { key: "C", text: "轻轻按摩，贴创可贴" }], answer: "A" },
{ id: 4, type: "choice" as const, content: "运动员在足球比赛时要求穿护袜带护腿板，其主要目的是", options: [{ key: "A", text: "看起来很酷" }, { key: "B", text: "安全防护" }, { key: "C", text: "能跑得快" }], answer: "B" },
{ id: 5, type: "choice" as const, content: "体育锻炼中，有效预防运动损伤的正确做法是", options: [{ key: "A", text: "运动过程中嬉笑打闹，动作幅度大" }, { key: "B", text: "拒绝保护帮助，完成动作犹豫不决" }, { key: "C", text: "运动前热身，运动后放松，运动负荷适宜" }], answer: "C" },
{ id: 6, type: "choice" as const, content: "属于急性闭合性软组织损伤的是", options: [{ key: "A", text: "扭伤" }, { key: "B", text: "擦伤" }, { key: "C", text: "割伤" }], answer: "A" },
{ id: 7, type: "choice" as const, content: "需要紧急医疗救助时，应拨打的急救电话号码是", options: [{ key: "A", text: "110" }, { key: "B", text: "119" }, { key: "C", text: "120 或 999" }], answer: "C" },
{ id: 8, type: "choice" as const, content: "在家中闻到浓烈的煤气异味时，第一时间正确的做法是", options: [{ key: "A", text: "打开门窗，关掉阀门" }, { key: "B", text: "打开抽油烟机" }, { key: "C", text: "打电话求救" }], answer: "A" },
{ id: 9, type: "choice" as const, content: "在厨房炒菜发现油锅起火时，下面正确的处理方法是", options: [{ key: "A", text: "关闭燃气，盖上锅盖或湿布" }, { key: "B", text: "浇水扑火" }, { key: "C", text: "关门逃离" }], answer: "A" },
{ id: 10, type: "choice" as const, content: "电器起火，第一时间正确的做法是", options: [{ key: "A", text: "切断电源" }, { key: "B", text: "用湿布拍打" }, { key: "C", text: "用水浇灭" }], answer: "A" },
{ id: 11, type: "choice" as const, content: "消防安全宣传日是", options: [{ key: "A", text: "10 月 19 日" }, { key: "B", text: "11 月 9 日" }, { key: "C", text: "1 月 9 日" }], answer: "B" },
{ id: 12, type: "choice" as const, content: "在密闭环境下使用煤炉取暖、做饭，可能产生大量的有害气体积蓄在室内，会造成燃气中毒，导致机体缺氧。这种有害气体是", options: [{ key: "A", text: "氨气" }, { key: "B", text: "氮气" }, { key: "C", text: "一氧化碳" }], answer: "C" },
{ id: 13, type: "choice" as const, content: "体育课上要避免运动意外伤害的发生，以下正确的做法是", options: [{ key: "A", text: "随意闯入其他运动场地" }, { key: "B", text: "无保护下做有危险的器械动作" }, { key: "C", text: "在指定区域内有序开展活动" }], answer: "C" },
{ id: 14, type: "choice" as const, content: "下列是防暑降温药品的是", options: [{ key: "A", text: "藿香正气水" }, { key: "B", text: "阿司匹林" }, { key: "C", text: "维生素 C" }], answer: "A" },
{ id: 15, type: "choice" as const, content: "火灾发生时，应拨打的求助电话号码是", options: [{ key: "A", text: "12121" }, { key: "B", text: "119" }, { key: "C", text: "114" }], answer: "B" },
{ id: 16, type: "choice" as const, content: "当你正在五楼的教室上课时，如果发生了地震，正确的做法是", options: [{ key: "A", text: "冲出教室，找电梯逃生" }, { key: "B", text: "跳出窗户逃生" }, { key: "C", text: "躲至桌下，远离窗户，保护头部" }], answer: "C" },
{ id: 17, type: "choice" as const, content: "某同学活动时不小心摔倒，用手撑地，导致手腕疼痛无法活动。以下正确的做法是", options: [{ key: "A", text: "用一本厚书托起受伤的手腕并到医务室进一步处理" }, { key: "B", text: "立刻按摩疼痛部位" }, { key: "C", text: "用热毛巾敷在手腕处" }], answer: "A" },
{ id: 18, type: "choice" as const, content: "在游泳前，正确的做法是", options: [{ key: "A", text: "做好充分准备活动后下水" }, { key: "B", text: "换好衣服后直接跳下水" }, { key: "C", text: "不做准备活动往身上浇水后下水" }], answer: "A" },
{ id: 19, type: "choice" as const, content: "体育锻炼时准备活动的主要作用是", options: [{ key: "A", text: "消耗过多的体能" }, { key: "B", text: "激活身体各部位，避免损伤" }, { key: "C", text: "降低心率" }], answer: "B" },
{ id: 20, type: "choice" as const, content: "人被犬咬伤后应立即用大量流动水冲洗伤口，并尽快去正规医院注射抗狂犬病血清和", options: [{ key: "A", text: "狂犬病疫苗" }, { key: "B", text: "流感疫苗" }, { key: "C", text: "乙肝疫苗" }], answer: "A" },
{ id: 21, type: "choice" as const, content: "流行性感冒是由流感病毒引起的急性呼吸道传染病，病原体有甲、乙、丙三型，其主要传播途径是", options: [{ key: "A", text: "飞沫传播" }, { key: "B", text: "血液传播" }, { key: "C", text: "虫媒传播" }], answer: "A" },
{ id: 22, type: "choice" as const, content: "发热，也叫 “发烧”，是疾病的体征之一。健康人的体温一般为", options: [{ key: "A", text: "33℃至 35℃" }, { key: "B", text: "36.1℃至 37.3℃" }, { key: "C", text: "38℃至 39℃" }], answer: "B" },
{ id: 23, type: "choice" as const, content: "日常生活中，下列有助于预防传染病的措施是", options: [{ key: "A", text: "喝生水" }, { key: "B", text: "科学洗手" }, { key: "C", text: "吃不洁瓜果" }], answer: "B" },
{ id: 24, type: "choice" as const, content: "日常生活中用于消毒的酒精浓度是", options: [{ key: "A", text: "50%" }, { key: "B", text: "60%" }, { key: "C", text: "75%" }], answer: "C" },
{ id: 25, type: "choice" as const, content: "预防传染病有效的做法是", options: [{ key: "A", text: "养成健康的生活习惯" }, { key: "B", text: "每天早晚不刷牙" }, { key: "C", text: "在流动摊点乱吃东西" }], answer: "A" },
{ id: 26, type: "choice" as const, content: "下列经血液传播的传染病是", options: [{ key: "A", text: "流感" }, { key: "B", text: "乙肝" }, { key: "C", text: "红眼病" }], answer: "B" },
{ id: 27, type: "choice" as const, content: "肺结核的主要传播途径是", options: [{ key: "A", text: "呼吸道传播" }, { key: "B", text: "消化道传播" }, { key: "C", text: "虫媒传播" }], answer: "A" },
{ id: 28, type: "choice" as const, content: "以下可能会引起肠道传染病的行为是", options: [{ key: "A", text: "餐前洗手" }, { key: "B", text: "使用公筷" }, { key: "C", text: "吃不洁净食物" }], answer: "C" },
{ id: 29, type: "choice" as const, content: "以下疾病中属于传染病的是", options: [{ key: "A", text: "高血压" }, { key: "B", text: "心脏病" }, { key: "C", text: "水痘" }], answer: "C" },
{ id: 30, type: "choice" as const, content: "以下属于 “积极调控情绪” 的方法是", options: [{ key: "A", text: "积极运动，主动缓解压力" }, { key: "B", text: "用药物麻痹自己" }, { key: "C", text: "闷闷不乐，默不作声" }], answer: "A" },
{ id: 31, type: "choice" as const, content: "以下属于积极情绪的是", options: [{ key: "A", text: "乐观向上" }, { key: "B", text: "冲动愤怒" }, { key: "C", text: "难过悲伤" }], answer: "A" },
{ id: 32, type: "choice" as const, content: "以下属于消极情绪的是", options: [{ key: "A", text: "愉悦放松" }, { key: "B", text: "紧张焦虑" }, { key: "C", text: "阳光快乐" }], answer: "B" },
{ id: 33, type: "choice" as const, content: "坚持体育锻炼对心理发展的价值包括愉悦身心、缓解疲劳、展示能力和", options: [{ key: "A", text: "增强自信" }, { key: "B", text: "容易焦虑" }, { key: "C", text: "身心疲惫" }], answer: "A" },
{ id: 34, type: "choice" as const, content: "运动后正确的补水方法是", options: [{ key: "A", text: "少量多次" }, { key: "B", text: "多量少次" }, { key: "C", text: "多量多次" }], answer: "A" },
{ id: 35, type: "choice" as const, content: "初中《国家学生体质健康标准》测试项目包含体重指数、肺活量、800 米 / 1000 米、引体向上、仰卧起坐、坐位体前屈、50 米和", options: [{ key: "A", text: "立定跳远" }, { key: "B", text: "跳绳" }, { key: "C", text: "50 米 ×8" }], answer: "A" },
{ id: 36, type: "choice" as const, content: "提升下肢力量的有效练习方法是", options: [{ key: "A", text: "斜身引体" }, { key: "B", text: "俯卧撑" }, { key: "C", text: "深蹲起" }], answer: "C" },
{ id: 37, type: "choice" as const, content: "发展灵敏性的有效练习方法是", options: [{ key: "A", text: "马步静蹲" }, { key: "B", text: "绳梯练习" }, { key: "C", text: "平板支撑" }], answer: "B" },
{ id: 38, type: "choice" as const, content: "在体育锻炼中，通常用来控制运动强度的是", options: [{ key: "A", text: "安静心率" }, { key: "B", text: "靶心率" }, { key: "C", text: "最大心率" }], answer: "B" },
{ id: 39, type: "choice" as const, content: "室内发生火灾时，正确的逃生方式是", options: [{ key: "A", text: "湿毛巾捂住口鼻，低姿逃生" }, { key: "B", text: "坐电梯逃生" }, { key: "C", text: "高层开窗跳楼逃生" }], answer: "A" },
{ id: 40, type: "choice" as const, content: "对提高睡眠质量有积极性作用的是", options: [{ key: "A", text: "睡前大量进食" }, { key: "B", text: "睡前剧烈运动" }, { key: "C", text: "规律、适度的运动" }], answer: "C" },
{ id: 41, type: "choice" as const, content: "保护视力重要的方式有保持正确读写姿势和", options: [{ key: "A", text: "边吃饭，边看书" }, { key: "B", text: "养成良好的用眼卫生习惯" }, { key: "C", text: "昏暗光线下看书" }], answer: "B" },
{ id: 42, type: "choice" as const, content: "长时间近距离用眼后，我们应该", options: [{ key: "A", text: "继续近距离用眼直到完成再休息" }, { key: "B", text: "闭上眼睛用力揉搓" }, { key: "C", text: "远眺或做眼保健操" }], answer: "C" },
{ id: 43, type: "choice" as const, content: "“健康四大基石” 指合理膳食、适量运动、规律生活和", options: [{ key: "A", text: "晚睡早起" }, { key: "B", text: "心理平衡" }, { key: "C", text: "过度用眼" }], answer: "B" },
{ id: 44, type: "choice" as const, content: "健康不仅是身体没有疾病，而且是身体、心理、社会适应三者的完好状态。以下属于健康生活方式的是", options: [{ key: "A", text: "暴饮暴食" }, { key: "B", text: "情绪消极" }, { key: "C", text: "规律生活" }], answer: "C" },
{ id: 45, type: "choice" as const, content: "运动后，为了快速补充身体内流失的水分，以下正确的做法是", options: [{ key: "A", text: "大量饮用冰镇饮料" }, { key: "B", text: "大量饮用牛奶" }, { key: "C", text: "适量饮用淡盐水" }], answer: "C" },
{ id: 46, type: "choice" as const, content: "有关体育锻炼的良好习惯，以下选项中正确的是", options: [{ key: "A", text: "规律运动" }, { key: "B", text: "锻炼后不放松" }, { key: "C", text: "不做准备活动" }], answer: "A" },
{ id: 47, type: "choice" as const, content: "要做到合理膳食，以下选项中正确的是", options: [{ key: "A", text: "糖分口感好，可过量摄入" }, { key: "B", text: "多吃油炸食品" }, { key: "C", text: "适量搭配谷物、薯类" }], answer: "C" },
{ id: 48, type: "choice" as const, content: "如果体质健康测试结果显示肥胖状态，合理减脂的方式是", options: [{ key: "A", text: "吃减肥药" }, { key: "B", text: "合理膳食，适量运动" }, { key: "C", text: "每天只吃一顿饭" }], answer: "B" },
{ id: 49, type: "choice" as const, content: "有关体育锻炼的作用，以下选项中表述正确的是", options: [{ key: "A", text: "促进骨骼生长发育" }, { key: "B", text: "不利于培养坚强的意志品质" }, { key: "C", text: "不能促进大脑的发育" }], answer: "A" },
{ id: 50, type: "choice" as const, content: "在中长跑练习中，出现速度下降、喘粗气、疲惫不堪的感觉，这种现象在运动中称之为", options: [{ key: "A", text: "休克" }, { key: "B", text: "昏厥" }, { key: "C", text: "极点" }], answer: "C" },
{ id: 51, type: "choice" as const, content: "《国家学生体质健康标准》中判断肥胖的指标是", options: [{ key: "A", text: "身体质量指数（BMI）" }, { key: "B", text: "握力" }, { key: "C", text: "肺活量" }], answer: "A" },
{ id: 52, type: "choice" as const, content: "有助于预防青春期脊柱侧弯的方法是", options: [{ key: "A", text: "长时间躺在床上玩手机" }, { key: "B", text: "正确的站姿、坐姿" }, { key: "C", text: "长时间伏案" }], answer: "B" },
{ id: 53, type: "choice" as const, content: "以下最适合发展心肺耐力的项目是", options: [{ key: "A", text: "象棋" }, { key: "B", text: "射箭" }, { key: "C", text: "中长跑" }], answer: "C" },
{ id: 54, type: "choice" as const, content: "运动前，以下做法正确的是", options: [{ key: "A", text: "暴饮暴食" }, { key: "B", text: "充分热身" }, { key: "C", text: "不做热身" }], answer: "B" },
{ id: 55, type: "choice" as const, content: "运动后，以下做法正确的是", options: [{ key: "A", text: "立即坐下" }, { key: "B", text: "多喝冰水" }, { key: "C", text: "拉伸放松" }], answer: "C" },
{ id: 56, type: "choice" as const, content: "以下属于积极性休息的做法是", options: [{ key: "A", text: "经常熬夜" }, { key: "B", text: "适度体育锻炼" }, { key: "C", text: "晚睡晚起" }], answer: "B" },
{ id: 57, type: "choice" as const, content: "以下有利于青春期生长发育的做法是", options: [{ key: "A", text: "挑食偏食" }, { key: "B", text: "体育锻炼" }, { key: "C", text: "盲目节食" }], answer: "B" },
{ id: 58, type: "choice" as const, content: "以下练习方法有助于提高上肢力量的是", options: [{ key: "A", text: "斜身引体" }, { key: "B", text: "徒手深蹲" }, { key: "C", text: "高抬腿跑" }], answer: "A" },
{ id: 59, type: "choice" as const, content: "合理控制体重的方法主要包括加强体育锻炼和", options: [{ key: "A", text: "喝碳酸饮料" }, { key: "B", text: "合理膳食" }, { key: "C", text: "吃减肥药" }], answer: "B" },
{ id: 60, type: "choice" as const, content: "吸烟对身体的影响是", options: [{ key: "A", text: "促进身体健康" }, { key: "B", text: "促进生长发育" }, { key: "C", text: "有害健康" }], answer: "C" },
{ id: 61, type: "choice" as const, content: "冬天参加滑冰活动，应选择", options: [{ key: "A", text: "正规开放的冰场" }, { key: "B", text: "结冰的河道" }, { key: "C", text: "结冰的湖面" }], answer: "A" },
{ id: 62, type: "choice" as const, content: "田径比赛中，以下属于径赛项目的是", options: [{ key: "A", text: "铅球" }, { key: "B", text: "铁饼" }, { key: "C", text: "400 米" }], answer: "C" },
{ id: 63, type: "choice" as const, content: "田径比赛中，以下属于集体项目的是", options: [{ key: "A", text: "跳高" }, { key: "B", text: "铅球" }, { key: "C", text: "4×100 米接力" }], answer: "C" },
{ id: 64, type: "choice" as const, content: "足球比赛中裁判员判罚某个球员离场，出示", options: [{ key: "A", text: "绿牌" }, { key: "B", text: "黑牌" }, { key: "C", text: "红牌" }], answer: "C" },
{ id: 65, type: "choice" as const, content: "在奥运会上，中国三大球中唯一拿到过冠军的队伍是", options: [{ key: "A", text: "女子排球队" }, { key: "B", text: "女子足球队" }, { key: "C", text: "男子篮球队" }], answer: "A" },
{ id: 66, type: "choice" as const, content: "在端午节举行的中华传统体育类运动项目是", options: [{ key: "A", text: "足球" }, { key: "B", text: "篮球" }, { key: "C", text: "龙舟" }], answer: "C" },
{ id: 67, type: "choice" as const, content: "团队运动中，以下最重要的因素是", options: [{ key: "A", text: "个人表现" }, { key: "B", text: "团结协作" }, { key: "C", text: "推诿责任" }], answer: "B" },
{ id: 68, type: "choice" as const, content: "轮滑运动是由某个项目演变而来的，这个项目是", options: [{ key: "A", text: "滑冰" }, { key: "B", text: "体操" }, { key: "C", text: "武术" }], answer: "A" },
{ id: 69, type: "choice" as const, content: "田径比赛中，以下属于田赛项目的是", options: [{ key: "A", text: "100 米" }, { key: "B", text: "跳高" }, { key: "C", text: "800 米" }], answer: "B" },
{ id: 70, type: "choice" as const, content: "跳远比赛时，运动员试跳踩线犯规，裁判员举", options: [{ key: "A", text: "红旗" }, { key: "B", text: "白旗" }, { key: "C", text: "黄旗" }], answer: "A" },
{ id: 71, type: "choice" as const, content: "中国的国球是", options: [{ key: "A", text: "乒乓球" }, { key: "B", text: "足球" }, { key: "C", text: "网球" }], answer: "A" },
{ id: 72, type: "choice" as const, content: "以下描述正确的是", options: [{ key: "A", text: "无体育不教育" }, { key: "B", text: "体育与教育无关" }, { key: "C", text: "体育教育就是运动" }], answer: "A" },
{ id: 73, type: "choice" as const, content: "篮球比赛中，进攻队员脚踩三分线投篮命中，应判定得", options: [{ key: "A", text: "1 分" }, { key: "B", text: "2 分" }, { key: "C", text: "3 分" }], answer: "B" },
{ id: 74, type: "choice" as const, content: "标准的室内排球比赛，每队上场比赛人数为", options: [{ key: "A", text: "6 名" }, { key: "B", text: "8 名" }, { key: "C", text: "11 名" }], answer: "A" },
{ id: 75, type: "choice" as const, content: "2004 年 7 月 15 日，在北京举行的第三届中国足球博览会开幕式上，国际足联确认足球最早的发源地是", options: [{ key: "A", text: "中国淄博（临淄）" }, { key: "B", text: "印度新德里" }, { key: "C", text: "埃及开罗" }], answer: "A" },
{ id: 76, type: "choice" as const, content: "足球比赛中，掷界外球队员跳起掷球，应判罚为", options: [{ key: "A", text: "继续比赛" }, { key: "B", text: "黄牌警告" }, { key: "C", text: "违例，由对方掷界外球" }], answer: "C" },
{ id: 77, type: "choice" as const, content: "篮球比赛中进攻队员跳起投篮，球出手后比赛计时器时间走完比赛结束，球进篮筐，应判罚为", options: [{ key: "A", text: "进球无效" }, { key: "B", text: "进球有效" }, { key: "C", text: "技术犯规" }], answer: "B" },
{ id: 78, type: "choice" as const, content: "中国男子篮球职业联赛（CBA）比赛分为", options: [{ key: "A", text: "3 节" }, { key: "B", text: "4 节" }, { key: "C", text: "5 节" }], answer: "B" },
{ id: 79, type: "choice" as const, content: "篮球比赛中，运球队员在运球过程中双手将球拿起后，再继续运球，应判罚为", options: [{ key: "A", text: "继续比赛" }, { key: "B", text: "两次运球违例" }, { key: "C", text: "侵人犯规" }], answer: "B" },
{ id: 80, type: "choice" as const, content: "100 米比赛中，参赛选手哪个身体部位抵达终点线被视为完成比赛", options: [{ key: "A", text: "头" }, { key: "B", text: "手" }, { key: "C", text: "躯干" }], answer: "C" },
{ id: 81, type: "choice" as const, content: "以下属于中华传统体育类运动项目的是", options: [{ key: "A", text: "太极拳" }, { key: "B", text: "拳击" }, { key: "C", text: "柔术" }], answer: "A" },
{ id: 82, type: "choice" as const, content: "作为东道主观赛时，提倡的观赛礼仪是", options: [{ key: "A", text: "只为本队加油" }, { key: "B", text: "为双方队员加油喝彩" }, { key: "C", text: "诋毁或辱骂对方队员" }], answer: "B" },
{ id: 83, type: "choice" as const, content: "现场观看体育比赛后，正确的做法是", options: [{ key: "A", text: "走捷径尽快离场" }, { key: "B", text: "将杂物带出场外" }, { key: "C", text: "将垃圾留在座位" }], answer: "B" },
{ id: 84, type: "choice" as const, content: "使用兴奋剂不仅会危害运动员的身体健康，还严重违背了", options: [{ key: "A", text: "公平竞争原则" }, { key: "B", text: "合作原则" }, { key: "C", text: "互惠原则" }], answer: "A" },
{ id: 85, type: "choice" as const, content: "球出界，裁判未发现，运动员主动示意对方球权，这种体育品德属于", options: [{ key: "A", text: "追求卓越" }, { key: "B", text: "勇敢顽强" }, { key: "C", text: "诚实守信" }], answer: "C" },
{ id: 86, type: "choice" as const, content: "为中国夺得冬奥会 “首金” 的运动员是", options: [{ key: "A", text: "杨扬" }, { key: "B", text: "叶乔波" }, { key: "C", text: "武大靖" }], answer: "A" },
{ id: 87, type: "choice" as const, content: "在班级联赛中，如果与队友存在分歧，应该如何做", options: [{ key: "A", text: "埋怨队友" }, { key: "B", text: "各行其是" }, { key: "C", text: "协商达成共识" }], answer: "C" },
{ id: 88, type: "choice" as const, content: "积极参加体育运动，对青少年心理的影响是", options: [{ key: "A", text: "产生消极情绪" }, { key: "B", text: "提高心理韧性" }, { key: "C", text: "容易焦虑抑郁" }], answer: "B" },
{ id: 89, type: "choice" as const, content: "现代奥林匹克运动会每几年举办一次", options: [{ key: "A", text: "5 年" }, { key: "B", text: "4 年" }, { key: "C", text: "3 年" }], answer: "B" },
{ id: 90, type: "choice" as const, content: "被誉为 “现代奥林匹克之父” 的是", options: [{ key: "A", text: "马泰奥" }, { key: "B", text: "顾拜旦" }, { key: "C", text: "维凯拉斯" }], answer: "B" },
{ id: 91, type: "choice" as const, content: "奥运五环颜色从左至右依次为蓝，黄，黑，绿和", options: [{ key: "A", text: "紫" }, { key: "B", text: "红" }, { key: "C", text: "粉" }], answer: "B" },
{ id: 92, type: "choice" as const, content: "中国第一位正式参加奥运会的运动员是", options: [{ key: "A", text: "沈嗣良" }, { key: "B", text: "刘长春" }, { key: "C", text: "于希渭" }], answer: "B" },
{ id: 93, type: "choice" as const, content: "为中国夺得现代奥运会 “首金” 的射击运动员是", options: [{ key: "A", text: "许海峰" }, { key: "B", text: "王义夫" }, { key: "C", text: "杨凌" }], answer: "A" },
{ id: 94, type: "choice" as const, content: "在班级篮球比赛中一分惜败，应如何正确面对", options: [{ key: "A", text: "自暴自弃" }, { key: "B", text: "埋怨别人" }, { key: "C", text: "复盘改进" }], answer: "C" },
{ id: 95, type: "choice" as const, content: "在体育运动中，有效的交流应遵循的六个要点是：及时交流、保持专注、开放接纳、主动确认、沟通简洁和", options: [{ key: "A", text: "情绪发泄" }, { key: "B", text: "突出自我" }, { key: "C", text: "控制情绪" }], answer: "C" },
{ id: 96, type: "choice" as const, content: "课间 15 分钟，倡导同学们", options: [{ key: "A", text: "打开窗户，走出教室，享受阳光" }, { key: "B", text: "坐在教室聊天" }, { key: "C", text: "趴在桌上睡觉" }], answer: "A" },
{ id: 97, type: "choice" as const, content: "世界上第一个既举办过夏奥会又举办过冬奥会的城市是", options: [{ key: "A", text: "中国北京" }, { key: "B", text: "俄罗斯索契" }, { key: "C", text: "意大利都灵" }], answer: "A" },
{ id: 98, type: "choice" as const, content: "古代奥运会起源于", options: [{ key: "A", text: "古希腊" }, { key: "B", text: "古埃及" }, { key: "C", text: "古印度" }], answer: "A" },
{ id: 99, type: "choice" as const, content: "当面对比赛中的困难时，运动员应该展现的精神是", options: [{ key: "A", text: "放弃比赛" }, { key: "B", text: "抱怨队友" }, { key: "C", text: "勇敢顽强" }], answer: "C" },
{ id: 100, type: "choice" as const, content: "以下选项中体现优良体育道德的是", options: [{ key: "A", text: "不服从裁判判决" }, { key: "B", text: "故意弄伤对方" }, { key: "C", text: "自觉遵守规则" }], answer: "C" }]

export const examPaperJudgeQuestions: Question[] = [
{ id: 101, type: "judge" as const, content: "运动前，做好充分的准备活动可以有效地预防运动损伤。", answer: "T" },
{ id: 102, type: "judge" as const, content: "参加 800 米 / 1000 米测试时，为了节省体力，可以不做准备活动。", answer: "F" },
{ id: 103, type: "judge" as const, content: "轻度烫烧伤只损伤到皮肤表皮浅层，表现为皮肤表面变红，局部轻度红肿，无水泡，疼痛明显，创伤表面干燥。", answer: "T" },
{ id: 104, type: "judge" as const, content: "游泳时应选择有安全设施和救援人员的正规游泳场馆。", answer: "T" },
{ id: 105, type: "judge" as const, content: "某同学打篮球时踝关节扭伤，同伴立刻帮助他按摩。", answer: "F" },
{ id: 106, type: "judge" as const, content: "发生火灾时，报警人拨打火灾报警电话后，应该到门口或交通路口等待消防车到来。", answer: "T" },
{ id: 107, type: "judge" as const, content: "生活中暴饮暴食会造成消化不良，引起肚子痛，甚至上吐下泻。", answer: "T" },
{ id: 108, type: "judge" as const, content: "体育锻炼时，树立安全意识，提高避险能力，可以有效减少意外伤害的发生。", answer: "T" },
{ id: 109, type: "judge" as const, content: "遇到雷雨闪电时，可以在大树下避雨并使用手机。", answer: "F" },
{ id: 110, type: "judge" as const, content: "遇到大风天气时，应到大树下、广告牌下躲避。", answer: "F" },
{ id: 111, type: "judge" as const, content: "到山区露营，如遇到河水迅速上涨，要快速向河谷两岸高处撤离。", answer: "T" },
{ id: 112, type: "judge" as const, content: "高楼发生火灾时，应该乘坐电梯尽快逃离火场。", answer: "F" },
{ id: 113, type: "judge" as const, content: "清洁的空气、水、土壤、适宜的气候等良好的自然环境，是生命赖以生存和发展的基础。", answer: "T" },
{ id: 114, type: "judge" as const, content: "在马路上骑自行车时，应在自行车道骑行；如无自行车道应紧靠慢车道右侧骑行。", answer: "T" },
{ id: 115, type: "judge" as const, content: "对于大量出血的受伤人员，在专业救援人员未到现场之前应设法止血。", answer: "T" },
{ id: 116, type: "judge" as const, content: "轻微擦伤时可以用生理盐水洗净创面，伤口周围用酒精或双氧水消毒，用碘伏等涂抹伤口，也可以用创可贴保护伤口。", answer: "T" },
{ id: 117, type: "judge" as const, content: "擦伤伤口创面大，污染严重时要注射破伤风或抗病毒血清。", answer: "T" },
{ id: 118, type: "judge" as const, content: "发生闭合性骨折后，要尽快用固定材料将骨折端固定，不再活动伤处。", answer: "T" },
{ id: 119, type: "judge" as const, content: "高温、高湿、通风不良环境下，长时间从事繁重体力劳动或体育运动，容易发生中暑。", answer: "T" },
{ id: 120, type: "judge" as const, content: "在马路上踢球、滑旱冰、玩滑板等运动，可以提高个人技术，挑战自我，是件很惬意的事。", answer: "F" },
{ id: 121, type: "judge" as const, content: "运动时，如果踝关节扭伤应立即停止运动，并进行冷敷。", answer: "T" },
{ id: 122, type: "judge" as const, content: "在体育锻炼时，除了要做好充分的准备活动以外，还要检查活动场地是否安全。", answer: "T" },
{ id: 123, type: "judge" as const, content: "流感患者打喷嚏可以用手帕捂住口鼻，减少疾病传播的机会。", answer: "T" },
{ id: 124, type: "judge" as const, content: "传染病传播的三个基本条件是：传染源、传播途径和易感人群。", answer: "T" },
{ id: 125, type: "judge" as const, content: "餐前洗手可以降低病毒传播的风险。", answer: "T" },
{ id: 126, type: "judge" as const, content: "在流感高发期，流感患者应尽量不到人多拥挤、空气污浊的场所。", answer: "T" },
{ id: 127, type: "judge" as const, content: "在流感流行季节到来前接种流感疫苗，可减少感染的机率或减轻流感症状。", answer: "T" },
{ id: 128, type: "judge" as const, content: "“吃动平衡” 是指人体摄入的能量和人体消耗的能量保持动态平衡，它有助于保持健康体重。", answer: "T" },
{ id: 129, type: "judge" as const, content: "病原体也叫 “病原生物”，是能引起人和动植物传染病的微生物和寄生虫的统称。", answer: "T" },
{ id: 130, type: "judge" as const, content: "海姆立克急救法主要用于应对急性气道异物梗阻的紧急情况。", answer: "T" },
{ id: 131, type: "judge" as const, content: "易感人群是指对某种传染病具有免疫力的人群。", answer: "F" },
{ id: 132, type: "judge" as const, content: "传染病只危害个人、危害家庭，不危害社会。", answer: "F" },
{ id: 133, type: "judge" as const, content: "不生病、身体健康，就没有必要锻炼身体，每天坚持锻炼身体会耽误宝贵的学习时间。", answer: "F" },
{ id: 134, type: "judge" as const, content: "坚持每天有规律的体育运动，有助于拥有健康的体魄。", answer: "T" },
{ id: 135, type: "judge" as const, content: "合理膳食要做到多吃蔬菜，吃适量水果和薯类，以及适量的鱼、禽、蛋和瘦肉。", answer: "T" },
{ id: 136, type: "judge" as const, content: "人体必需的营养素包含糖类、脂类、蛋白质、维生素和矿物质等。", answer: "T" },
{ id: 137, type: "judge" as const, content: "运动开始前要进行热身，运动结束后要进行拉伸放松。", answer: "T" },
{ id: 138, type: "judge" as const, content: "喝碳酸饮料，是日常补充水分的主要途径。", answer: "F" },
{ id: 139, type: "judge" as const, content: "初中生正处于身体快速发育阶段，如果体重过低、超重或者肥胖，应合理膳食和加强体育锻炼。", answer: "T" },
{ id: 140, type: "judge" as const, content: "周末和父母一起锻炼，可以通过监测心率的方法，调控运动强度，做到科学锻炼。", answer: "T" },
{ id: 141, type: "judge" as const, content: "合理膳食就是多吃肉，少吃蔬菜。", answer: "F" },
{ id: 142, type: "judge" as const, content: "课余长时间使用手机、电脑上网，这是休息的好方式。", answer: "F" },
{ id: 143, type: "judge" as const, content: "健康仅仅是指身体没有疾病。", answer: "F" },
{ id: 144, type: "judge" as const, content: "青少年时期要注意培养自己良好的生活习惯，合理安排作息时间。", answer: "T" },
{ id: 145, type: "judge" as const, content: "青少年每天应摄取新鲜蔬菜、水果等维生素 C 含量丰富的食物。", answer: "T" },
{ id: 146, type: "judge" as const, content: "长期不吃早餐可能会诱发消化道疾病，影响身体健康。", answer: "T" },
{ id: 147, type: "judge" as const, content: "导致肥胖的主要因素包括遗传、饮食不当和缺乏运动等。", answer: "T" },
{ id: 148, type: "judge" as const, content: "长时间近距离用眼，容易引发视觉疲劳，长此以往导致视力减退。", answer: "T" },
{ id: 149, type: "judge" as const, content: "经常在昏暗的灯光下看书不会影响视力。", answer: "F" },
{ id: 150, type: "judge" as const, content: "长时间玩手机、电脑游戏，不会影响视力。", answer: "F" },
{ id: 151, type: "judge" as const, content: "经常参加体育活动有助于消除人的紧张、焦虑和孤独感。", answer: "T" },
{ id: 152, type: "judge" as const, content: "经常参加足球、篮球、排球等团队体育活动，能够使人感到集体的温暖，并在与同伴的相互交往中增进友谊。", answer: "T" },
{ id: 153, type: "judge" as const, content: "长期吸烟或被动吸烟可能会导致呼吸系统疾病。", answer: "T" },
{ id: 154, type: "judge" as const, content: "青春期经常参加体育锻炼可以促进身高增长。", answer: "T" },
{ id: 155, type: "judge" as const, content: "身体质量指数（BMI）是判断个体体重状况的依据。", answer: "T" },
{ id: 156, type: "judge" as const, content: "读书、学习时，如果不注意身体姿态，有可能引起脊柱变形。", answer: "T" },
{ id: 157, type: "judge" as const, content: "对青少年来说，不需要强调正确的坐姿和站姿。", answer: "F" },
{ id: 158, type: "judge" as const, content: "青少年充足的睡眠可以促进生长发育。", answer: "T" },
{ id: 159, type: "judge" as const, content: "户外运动有利于体内维生素 D 的合成，促进骨骼的健康发育。", answer: "T" },
{ id: 160, type: "judge" as const, content: "经常参加体育锻炼可以提升骨骼的抗弯、抗折、抗压能力。", answer: "T" },
{ id: 161, type: "judge" as const, content: "经常进行体育锻炼，可以使呼吸肌、心肌的力量增强，胸廓运动幅度和血管壁弹性加大，从而改善呼吸和心血管机能。", answer: "T" },
{ id: 162, type: "judge" as const, content: "定期体检有助于及早发现常见病。", answer: "T" },
{ id: 163, type: "judge" as const, content: "脸上长了 “青春痘” 不能自己用手随意挤压，以免感染。", answer: "T" },
{ id: 164, type: "judge" as const, content: "青春期会出现身高迅速增长，体重明显增加，心脏发育迅速，生殖器官、第二性征发育变化显著。", answer: "T" },
{ id: 165, type: "judge" as const, content: "经常参加体育活动有利于调节情绪，塑造健康向上、积极乐观的性格。", answer: "T" },
{ id: 166, type: "judge" as const, content: "长期科学运动比短期剧烈运动对降低焦虑更具有积极效果。", answer: "T" },
{ id: 167, type: "judge" as const, content: "面对压力时，人的机体常常产生一种自发的神经反应，这种反应是应激反应。", answer: "T" },
{ id: 168, type: "judge" as const, content: "只要注意休息、合理膳食，即使没有一个好的心态也是健康的。", answer: "F" },
{ id: 169, type: "judge" as const, content: "体育锻炼对于减轻焦虑和缓解抑郁有积极的作用。", answer: "T" },
{ id: 170, type: "judge" as const, content: "心理健康的人往往表现出乐观开朗、积极向上、热爱生活的状态。", answer: "T" },
{ id: 171, type: "judge" as const, content: "欣赏乒乓球比赛时，应从战术和技术等多方面分析和评论。", answer: "T" },
{ id: 172, type: "judge" as const, content: "正式排球比赛中，每队最多可以 3 次击球过网（拦网者触球不计入 3 次击球之内），否则就会被判四次击球犯规而失分。", answer: "T" },
{ id: 173, type: "judge" as const, content: "足球运动员在掷界外球时双脚可以同时离开地面。", answer: "F" },
{ id: 174, type: "judge" as const, content: "观赛前，观众适当了解该运动项目的基本规则，有利于更好地观赛，提高比赛理解能力。", answer: "T" },
{ id: 175, type: "judge" as const, content: "奥运会田径比赛中，200 米比赛时，为了取得更好成绩可以串跑道。", answer: "F" },
{ id: 176, type: "judge" as const, content: "在速度滑冰比赛中，为捕捉精彩瞬间，可以打开闪光灯拍照。", answer: "F" },
{ id: 177, type: "judge" as const, content: "在投掷项目的比赛中设有投掷区，投掷时脚踩到投掷区以外的地面，不属于犯规。", answer: "F" },
{ id: 178, type: "judge" as const, content: "在班级拔河比赛中，拔河队员齐心协力是取胜的关键，啦啦队员的鼓励助威不重要。", answer: "F" },
{ id: 179, type: "judge" as const, content: "比赛场上，当一个国家的国歌奏响，国旗升起之时，应该肃然起立，向国旗行注目礼。", answer: "T" },
{ id: 180, type: "judge" as const, content: "正面双手垫球是排球运动中最基本的技术之一，常用于接发球和防守。", answer: "T" },
{ id: 181, type: "judge" as const, content: "影响身高的主要因素包括遗传因素、激素水平、营养状况和体力活动。", answer: "T" },
{ id: 182, type: "judge" as const, content: "立定跳远测试时，落地后不慎后倒，手后撑触地，距离依然应从脚落地的位置开始丈量。", answer: "F" },
{ id: 183, type: "judge" as const, content: "在进行坐位体前屈测试时，可以借助同伴帮助以取得更好的成绩。", answer: "F" },
{ id: 184, type: "judge" as const, content: "100 米比赛中，运动员挤撞或阻挡妨碍其他运动员前进，应取消该运动员的比赛资格。", answer: "T" },
{ id: 185, type: "judge" as const, content: "奥运会足球比赛时，双方首发上场各有 11 名队员。", answer: "T" },
{ id: 186, type: "judge" as const, content: "乒乓球比赛中，球还未落到球台就将球击回是符合规则的。", answer: "F" },
{ id: 187, type: "judge" as const, content: "现代科学技术的高速发展有力地提高了奥林匹克运动的水平和成绩。", answer: "T" },
{ id: 188, type: "judge" as const, content: "奥林匹克格言：更快、更高、更强 —— 更团结。", answer: "T" },
{ id: 189, type: "judge" as const, content: "体育比赛不仅是体力和技能的比拼，也蕴含着智慧的较量。", answer: "T" },
{ id: 190, type: "judge" as const, content: "2022 年北京冬奥会、冬残奥会主题口号是：一起向未来。", answer: "T" },
{ id: 191, type: "judge" as const, content: "奥林匹克五环标志象征着五大洲的团结，象征着全世界的运动员在奥运会上欢聚一堂。", answer: "T" },
{ id: 192, type: "judge" as const, content: "残奥会能够促进残疾人事业发展，形成尊重、关心和帮助残疾人的社会氛围。", answer: "T" },
{ id: 193, type: "judge" as const, content: "在班级 4×100 米接力跑比赛中，安排起跑最快的选手作为第一棒，冲刺能力最强的选手作为最后一棒，直道技术较好的选手跑第二棒，弯道技术较好的选手跑第三棒。", answer: "T" },
{ id: 194, type: "judge" as const, content: "在足球赛中，既要展示自我又要与同伴合作配合。", answer: "T" },
{ id: 195, type: "judge" as const, content: "优良的意志品质是与生俱来的，无法在实践活动中通过克服困难逐渐形成。", answer: "F" },
{ id: 196, type: "judge" as const, content: "体育运动中，每个人都应该在遵守规则的前提下，进行公平竞争。", answer: "T" },
{ id: 197, type: "judge" as const, content: "奥运会不断践行着公平公正的原则，不断传递着体育道德的正能量。", answer: "T" },
{ id: 198, type: "judge" as const, content: "参与体育比赛要有正确的胜负观，做到胜不骄、败不馁。", answer: "T" },
{ id: 199, type: "judge" as const, content: "体育比赛中，要团结队友、尊重对手。", answer: "T" },
{ id: 200, type: "judge" as const, content: "篮球比赛过程中只要个人发挥好就可以了，其他队友发挥好与不好都无所谓。", answer: "F" }
]
